# Generated by Django 5.0.3 on 2024-04-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_image_url',
            field=models.URLField(null=True),
        ),
    ]
