# Generated by Django 5.0.3 on 2024-04-08 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_customer_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='carts',
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table='cart items',
        ),
        migrations.AlterModelTable(
            name='rating',
            table='ratings',
        ),
    ]
