# Generated by Django 5.0.3 on 2024-04-09 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_cart_table_alter_cartitem_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
    ]
