# Generated by Django 5.0.4 on 2024-04-17 16:33

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': [], 'verbose_name': 'Abstract Model', 'verbose_name_plural': 'Abstract Models'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': [], 'verbose_name': 'Abstract Model', 'verbose_name_plural': 'Abstract Models'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='reviewText',
        ),
        migrations.AddField(
            model_name='cart',
            name='updated_last_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AddField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUId'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 4, 17, 17, 32, 51, 775985), verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='updated_last_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUId'),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 4, 17, 17, 32, 56, 412878), verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_last_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AddField(
            model_name='customer',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUId'),
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 4, 17, 17, 33, 0, 217823), verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='updated_last_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AddField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUId'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 4, 17, 17, 33, 4, 459024), verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='updated_last_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUId'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 4, 17, 17, 33, 8, 145070), verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='updated_last_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AddField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUId'),
        ),
        migrations.AddField(
            model_name='rating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 4, 17, 17, 33, 13, 630686), verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='updated_last_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AddField(
            model_name='rating',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUId'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', related_query_name='item', to='store.cart'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='store.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', related_query_name='order', to=settings.AUTH_USER_MODEL, verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.TextField(choices=[('delivered', 'Delivered'), ('pending', 'Pending'), ('en route', 'En route')], default='pending', max_length=10, verbose_name='Order Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='placed_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Placed At'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', related_query_name='item', to='store.order', verbose_name='Orders'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='store.product', verbose_name='Products'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', related_query_name='rating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rating',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', related_query_name='rating', to='store.product'),
        ),
    ]
