# Generated by Django 5.0.4 on 2024-04-17 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='updated_last_at',
            new_name='last_updated',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='updated_last_at',
            new_name='last_updated',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='updated_last_at',
            new_name='last_updated',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='updated_last_at',
            new_name='last_updated',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='updated_last_at',
            new_name='last_updated',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='updated_last_at',
            new_name='last_updated',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='updated_last_at',
            new_name='last_updated',
        ),
    ]
