# Generated by Django 5.0.4 on 2024-04-17 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_updated_last_at_cart_last_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
    ]
