# Generated by Django 5.0.3 on 2024-03-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', 'initial_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['first_name', 'last_name', 'email'], name='customers_first_n_fb52c9_idx'),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customers',
        ),
    ]
